// Code generated by mdatagen. DO NOT EDIT.

package metadatatest

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/otel/sdk/metric/metricdata"
	"go.opentelemetry.io/otel/sdk/metric/metricdata/metricdatatest"

	"github.com/tf-rob-w/otel-collector-filter-remap-processor/filterremapprocessor/internal/metadata"
	"go.opentelemetry.io/collector/component/componenttest"
)

func TestSetupTelemetry(t *testing.T) {
	testTel := componenttest.NewTelemetry()
	tb, err := metadata.NewTelemetryBuilder(testTel.NewTelemetrySettings())
	require.NoError(t, err)
	defer tb.Shutdown()
	tb.ProcessorFilterRemapCountSpansSampled.Add(context.Background(), 1)
	tb.ProcessorFilterRemapForwardQueueOverflows.Add(context.Background(), 1)
	tb.ProcessorFilterRemapForwardTraceLatency.Record(context.Background(), 1)
	tb.ProcessorFilterRemapMaxRetentionTickProcessingTime.Record(context.Background(), 1)
	tb.ProcessorFilterRemapNewTraceIDReceived.Add(context.Background(), 1)
	tb.ProcessorFilterRemapOttlEvaluationError.Add(context.Background(), 1)
	tb.ProcessorFilterRemapSpanDecisionLatency.Record(context.Background(), 1)
	tb.ProcessorFilterRemapSpansPerTrace.Record(context.Background(), 1)
	tb.ProcessorFilterRemapTickProcessingTime.Record(context.Background(), 1)
	tb.ProcessorFilterRemapTraceDroppedTooEarly.Add(context.Background(), 1)
	tb.ProcessorFilterRemapTraceRemapLatency.Record(context.Background(), 1)
	tb.ProcessorFilterRemapTracesOnMemory.Record(context.Background(), 1)
	AssertEqualProcessorFilterRemapCountSpansSampled(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualProcessorFilterRemapForwardQueueOverflows(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualProcessorFilterRemapForwardTraceLatency(t, testTel,
		[]metricdata.HistogramDataPoint[int64]{{}}, metricdatatest.IgnoreValue(),
		metricdatatest.IgnoreTimestamp())
	AssertEqualProcessorFilterRemapMaxRetentionTickProcessingTime(t, testTel,
		[]metricdata.HistogramDataPoint[int64]{{}}, metricdatatest.IgnoreValue(),
		metricdatatest.IgnoreTimestamp())
	AssertEqualProcessorFilterRemapNewTraceIDReceived(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualProcessorFilterRemapOttlEvaluationError(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualProcessorFilterRemapSpanDecisionLatency(t, testTel,
		[]metricdata.HistogramDataPoint[int64]{{}}, metricdatatest.IgnoreValue(),
		metricdatatest.IgnoreTimestamp())
	AssertEqualProcessorFilterRemapSpansPerTrace(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualProcessorFilterRemapTickProcessingTime(t, testTel,
		[]metricdata.HistogramDataPoint[int64]{{}}, metricdatatest.IgnoreValue(),
		metricdatatest.IgnoreTimestamp())
	AssertEqualProcessorFilterRemapTraceDroppedTooEarly(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualProcessorFilterRemapTraceRemapLatency(t, testTel,
		[]metricdata.HistogramDataPoint[int64]{{}}, metricdatatest.IgnoreValue(),
		metricdatatest.IgnoreTimestamp())
	AssertEqualProcessorFilterRemapTracesOnMemory(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())

	require.NoError(t, testTel.Shutdown(context.Background()))
}
